#!/bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod1
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

function kb() {
  key=$1
  shift
  hc keybind $key spawn ~/.config/keybindings.sh $*
}

kb $Mod-Shift-e logout

kb $Mod-Return shell
kb $Mod-Shift-Return shell_attach

kb $Mod-d launcher
kb $Mod-Pause taskbar_toggle
kb $Mod-Shift-Pause keyboard_layout_toggle

kb XF86AudioPlay music_playpause
kb Control-XF86AudioPlay music_stop
kb XF86AudioNext music_next
kb XF86AudioPrev music_prev
kb Control-XF86AudioRaiseVolume music_raise
kb Control-XF86AudioLowerVolume music_lower

kb XF86AudioRaiseVolume audio_raise
kb XF86AudioLowerVolume audio_lower
kb XF86AudioMute audio_output_toggle
kb Control-XF86AudioMute audio_output_headphones

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( ampersand eacute quotedbl apostrophe parenleft minus egrave underscore ccedilla agrave )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-Up    resize up +$RESIZESTEP
hc keybind $Mod-Control-Down  resize down +$RESIZESTEP
hc keybind $Mod-Control-Left  resize left +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Up    focus up
hc keybind $Mod-Down  focus down
hc keybind $Mod-Left  focus left
hc keybind $Mod-Right focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Right shift right

hc set frame_border_normal_color '#ffcccc'
hc set frame_border_active_color '#ccffcc'
hc set frame_bg_transparent 1
hc set frame_border_width 1
hc set window_border_width 0
hc set window_border_inner_width 0
hc set frame_gap 16
hc set window_gap 0
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1
hc set swap_monitors_to_get_tag 0
hc set default_frame_layout 3
# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

herbstclient set tree_style '╾│ ├└╼─┐'

# multi monitor
hc detect_monitors
for i in $(seq 0 $(($(hc list_monitors | wc -l)-1)))
do
  hc pad $i "" "" 25 ""
done

# ready
hc unlock
for i in $(seq 1 1000)
do
  systemd-notify --ready
done
